name: 'Terraform Destroy'

on:
  workflow_dispatch: 

permissions:
  id-token: write
  contents: read

jobs:
  destroy:
    name: 'Terraform Destroy'
    runs-on: ubuntu-latest
    
    env:
      AWS_REGION: "${{ values.aws_region }}"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::276451917813:role/Github_actions-administrator_access
          aws-region: ${{ '${{ env.AWS_REGION }}' }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy
        run: terraform destroy -auto-approve